













ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "student_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "parent_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "parent_student_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "staff_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "school_years" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "terms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subjects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teacher_subject_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "adviser_access_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "anecdotal_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "anecdotal_record_followups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "referrals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "health_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "home_visitation_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "adm_learner_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "adm_parent_meetings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "adm_modules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "attendance_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "grade_components" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "student_grades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "final_grades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "student_risk_assessments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "record_flags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "student_reflections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "report_cards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
